# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
version: '3'
services:
  solr:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/solr:${PRIMERO_TAG:-latest}'
    env_file:
      - docker/defaults.env
    volumes:
      - solr_cores:/var/solr
    restart: always
  application:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/application:${PRIMERO_TAG:-latest}'
    depends_on:
      - solr
    volumes:
      - public:/share/public
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
    stdin_open: true
    tty: true
    restart: always
  worker:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/application:${PRIMERO_TAG:-latest}'
    depends_on:
      - solr
    volumes:
      - storage:/srv/primero/application/storage
    env_file:
      - docker/defaults.env
    command: ["primero-worker"]
    restart: always
volumes:
  database:
  public:
  solr_cores:
  storage:
  certbot_certificates:
  certbot_challenges:
  selfsigned_certs:
