test:
  solr:
    hostname: primero_solr_1
    port: 8983
    log_level: OFF
    pid_dir: tmp/pids
    path: /solr/primero-test
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
